print("Une partie de ce texte\r\nse trouve sur la ligne suivante.")
print("Ceci est un A avec un accent grave : \xC0.")
print("Ceci est un caractère dessiné : \u2562.")
print("Et voici un retour chariot: \266.")
print("Ceci est le signe de la division : \xF7.")
